baseurl = "http://castellafactory.github.io"
languageCode = "ja"
title = "カステラ工場"
hasCJKLanguage = true
googleAnalytics = "UA-75160489-1"

[params]
Author = "CastellaFactory"
Copyright = "CastellaFactory"
GitHubUser = "CastellaFactory"
LanguageCode = "ja"
LaunchYear = 2016
Locale = "ja_JP"
PoweredByHugo = 'True'
SidebarRecentLimit = 5
Subtitle = "カステラを作る工場です"
TaxonomiesInSidebar = [ 'tags' ]

[taxonomies]
tag = "tags"

[menu]
[[menu.social]]
name = 'Github'
pre = '<i class="fa fa-fw fa-github-square"></i>' 
url = 'https://github.com/CastellaFactory'
[[menu.top]]
name = 'About'
url = '/about'
